site_name: Ethan Jahn

nav:
  - Home: index.md
  - Bio: bio.md
  - Curriculum Vitae: cv.md
  - Galaxy Simulations Research: galaxysimulationresearch.md
  - High Performance Computing: hpc.md
  - Teaching: teaching.md
  - Science Communication: scicom.md
  - Artistic Expression of Original Research: aeor.md
  - Salon: salon.md
  - Digital Art: digitalart.md
  - Generative Code Art: generativecodeart.md
  - Film Photography: filmphotography.md
  - Tunez: music.md
  - Macrostructures of the Microcosmos: spacezine.md
  - Wizardz of Odd Zine: wizardz.md
  - Digital Garden: digigarden.md

theme: 
  name: material
  features:
    - header.autohide
  font:
    text: Space Grotesk
  favicon: null

# extra:
#   copyright: "© Ethan Jahn 2024"

extra_css:
  - assets/stylesheets/extra.css

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.html

extra_javascript:
  - assets/scripts/randombg.js
